### ISSUE TITLE
Circular loading of installed providers detected

### ISSUE THREAD

**Issue by dhakehurst** [beijunyi/ParallelGit#9]
final URI uri = URI.create("GFS:http://....../example1.git");
final FileSystem fs1 = FileSystems.getFileSystem(uri);

I would expect this to return null, if newFileSystem has not been called, but I get,

java.util.ServiceConfigurationError: java.nio.file.spi.FileSystemProvider: Provider com.beijunyi.parallelgit.filesystem.GitFileSystemProvider could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at java.nio.file.spi.FileSystemProvider.loadInstalledProviders(FileSystemProvider.java:119)
	at java.nio.file.spi.FileSystemProvider.access$000(FileSystemProvider.java:77)
	at java.nio.file.spi.FileSystemProvider$1.run(FileSystemProvider.java:169)
	at java.nio.file.spi.FileSystemProvider$1.run(FileSystemProvider.java:166)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.nio.file.spi.FileSystemProvider.installedProviders(FileSystemProvider.java:166)
	at java.nio.file.FileSystems.getFileSystem(FileSystems.java:219)
	at ....

Caused by: java.lang.Error: Circular loading of installed providers detected
	at java.nio.file.spi.FileSystemProvider.installedProviders(FileSystemProvider.java:161)
	at com.beijunyi.parallelgit.filesystem.GitFileSystemProvider.getInstalledProvider(GitFileSystemProvider.java:219)
	at com.beijunyi.parallelgit.filesystem.GitFileSystemProvider.<clinit>(GitFileSystemProvider.java:30)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 34 more

**Comment by phoenixchinar** [comment]
Calling FileSystemProvider.installedProviders(); by anyone before a single GitFileSystem has been instantiated causes a circular dependency. This also happens when trying to run under GraalVM with node starting jvm. The node process tries to get all the installedProviders causing circular dependency exception.

I think the function
```  @Nonnull
  private static GitFileSystemProvider getInstalledProvider() {
    GitFileSystemProvider ret = null;
    for(FileSystemProvider provider : FileSystemProvider.installedProviders()) {
      if(provider instanceof GitFileSystemProvider) {
        ret = (GitFileSystemProvider) provider;
        break;
      }
    }
    if(ret == null)
      ret = new GitFileSystemProvider();
    return ret;
  }
```

can simply be replaced with below as the only call to this is during static initialization.

```  @Nonnull
  private static GitFileSystemProvider getInstalledProvider() {
    return new GitFileSystemProvider();
  }
```

**Comment by JulienBurnet86** [comment]
Hi @phoenixchinar ,
We had a similar issue using parallelgit in a Quarkus application. Your suggestion fixed the issue, what about creating a merge request ?
Does @beijunyi still maintains this project ?

Thank you,

**Comment by phoenixchinar** [comment]
@beijunyi 

Please take a look at the #12 , and let us know if you will be able to merge this.

Thanks
